### ISSUE TITLE
Fix assumptions about train matrix path and scores file

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/Predict-TF-Binding#9]
In my testing, I put the scores file in a directory separate from the python scripts

```
$ pwd
/Users/dcl9/Code/python/SVR_models
$ python SVR_model_maker.py -i /Users/dcl9/Data/svr-model-maker/E2F1-cust2-scores_normalized.txt -c 1 -p 0.1
```

The call to run `svm-train` fails with `can't open model file /Users/dcl9/Data/svr-model-maker/E2F1-cust2-scores_normalized_SVR-model_train_matrix_1.txt.model`

The python script creates the matrix file in the current working directory, but the `svm-train` step expects it to be in the same directory as the scores file.

```
_____  Running SVR_model_maker _____
Running full libsvm

Finding good sequences from the pbmfile to use for SVR
Initially found 5643 sequences
list is too big, reducing size to 1000 sequences
with reverse complements: 2000
Using 2000 sequences (includes reverse complements)
Using about 1600 sequences (+/-1) out of 2000 for training the model

Running SVR on round 1 of 5
Generating the matrix files...
Training the model for run 1 ...
Testing the model for run 1 ...
can't open model file /Users/dcl9/Data/svr-model-maker/E2F1-cust2-scores_normalized_SVR-model_train_matrix_1.txt.model

Traceback (most recent call last):
  File "SVR_model_maker.py", line 574, in <module>
    libsvm_run(c,p,pbmfile)
  File "SVR_model_maker.py", line 404, in libsvm_run
    SCC =  float(string.split(out[-2])[-2]) #the output is a list of strings (lines), the last word in the last line (with info) is the R squared
IndexError: list index out of range
```

Obviously, if the working directory and the directory of the scores file are the same, this runs without issue.

**Comment by dleehr** [comment]
Issue here is that svm-train, by default, writes files in the current working directory.
However, svm-train does allow the model file to be specified.
